# -*- coding: utf-8 -*-
"""Problem1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S4ud1Xx6kJbbvyepXGdFZ8fA90DYBlGP

**Problem 1**
"""

import random
massDist = (0.2,0.4,0.1,0.1,0.1,0.1)
def roll(massDist):
    randRoll = random.random() # in [0,1]
    sum = 0
    result = 1
    for mass in massDist:
        sum += mass
        if randRoll < sum:
            return result
        result+=1

def dice(massDict):
  step = 0;
  numstep = 0;
  for i in range(100000):
    for i in range(250):
      result = roll(massDict)
      # print("You rolled",result)
      if result==1 or result==2: step=max(0,step-1)
      elif result>=3 and result<=5: step=step+1
      else: 
        result1 = roll(massDict)
        step=step+result1
    if step>60: numstep=numstep+1
  return numstep

numstep = dice(massDist)
print("Probability = ",numstep/100000)